FROM tensorflow/tensorflow:2.5.0

WORKDIR /home/pepr
COPY . .

RUN apt update && apt upgrade -y

RUN apt install -y texlive zip

RUN pip install --upgrade pip
RUN pip install .
RUN pip install jupyter notebook