FROM tensorflow/tensorflow:2.5.0

WORKDIR /home/pepr
COPY . .

RUN apt update && apt upgrade -y

RUN DEBIAN_FRONTEND=noninteractive apt install -y texlive-full zip

RUN pip install --upgrade pip
RUN pip install .
RUN pip install jupyter notebook