FROM tensorflow/tensorflow:2.4.1

WORKDIR /home/pepr
COPY . .

RUN apt update && apt upgrade -y

RUN apt install -y texlive

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -e .