# Attack Parameters
attack_pars:
  - attack_type: "mia"
    attack_alias: "MIA Tutorial"
    number_shadow_models: 100
    shadow_training_set_size: 2500
    path_to_dataset_data: "datasets/cifar100_data.npy"
    path_to_dataset_labels: "datasets/cifar100_labels.npy"
    number_classes: 100
    create_compile_shadow_model: "create_compile_shadow_model"
    shadow_epochs: 100
    shadow_batch_size: 50
    create_compile_attack_model: "create_compile_attack_model"
    attack_epochs: 50
    attack_batch_size: 50
    target_model_paths:
    - "data/target_model_mia"
  - attack_type: "gmia"
    attack_alias: "GMIA Tutorial"
    number_reference_models: 100
    reference_training_set_size: 10000
    path_to_dataset_data: "datasets/fmnist_data.npy"
    path_to_dataset_labels: "datasets/fmnist_labels.npy"
    number_classes: 10
    create_compile_model: "create_compile_reference_model"
    reference_epochs: 50
    reference_batch_size: 50
    hlf_metric: "cosine"
    hlf_layer_number: 10
    number_target_records: 25
    target_model_paths:
    - "data/target_model_gmia"

# Data Configuration
data_conf:
  - shadow_indices_path: "datasets/shadow_ref_indices.npy"
    target_indices_path: "datasets/target_indices.npy"
    evaluation_indices_path: "datasets/evaluation_indices.npy"
    record_indices_per_target_path: "datasets/record_indices_per_target.npy"
  - reference_indices_path: "datasets/shadow_ref_indices.npy"
    target_indices_path: "datasets/target_indices.npy"
    evaluation_indices_path: "datasets/evaluation_indices.npy"
    record_indices_per_target_path: "datasets/record_indices_per_target.npy"